[project]
name = "med-llm-jp"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12.8"
dependencies = [
    "datasets>=3.5.0",
    "openai>=1.70.0",
    "py2slack>=0.4.1",
    "python-dotenv>=1.1.0",
]
